name: PersonalWorld
main: personal.world.PersonalWorld
version: 0.3

commands:
  personalworld:
    description: Teleport to your personal world.
    usage: /personalworld
    aliases: [PW]
    