name: PersonalWorld
main: personal.world.PersonalWorld
version: 0.6.2

commands:
  personalworld:
    description: Teleport to your personal world.
    usage: /personalworld
    aliases: [pw]  
  personalworldadmin:
    description: Admin of PersonalWorld
    usage: /personalworld
    aliases: [pwadmin]    
permissions:
  personalworld.tp:
    default: true
    description: 傳送 
    
  personalworld.tpOther:
    default: true
    description: 傳送其他世界
    
  personalworld.info:
    default: true
    description: 查看世界權限
    
  personalworld.add:
    default: true
    description: 新增世界權限
    
  personalworld.remove:
    default: true
    description: 移除世界權限