name: PersonalWorld
main: personal.world.PersonalWorld
version: 0.6.1

commands:
  personalworld:
    description: Teleport to your personal world.
    usage: /personalworld
    aliases: [pw]   
permissions:
  personalworld.tp:
    default: op
    description: 主要權限  
  personalworld.tp.other:
    default: op
    description: 主要權限